// Generates OKF reserved `index.md` files (progressive-disclosure listings) for
// a docs bundle. One `index.md` per non-empty directory listing its concepts
// (`* [Title](./file.md) - description`) and sub-directories; the root also
// carries `okf_version`. Deterministic and idempotent — regenerated by the
// migration. `index.md`/`log.md` are reserved and never listed as concepts.
import fs from "node:fs";
import path from "node:path";
import { parseFrontmatter } from "../frontmatter";
import { parseFilename } from "../parser";
import { isReservedOkfFile, OKF_SPEC_VERSION } from "../okf";

const IGNORED_DIRS = new Set([".git", "node_modules", "dist", "files", "images"]);

interface ConceptEntry {
  file: string;
  title: string;
  description: string;
}

function conceptsAndDirs(dir: string): { concepts: ConceptEntry[]; subdirs: string[] } {
  const concepts: ConceptEntry[] = [];
  const subdirs: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isSymbolicLink() || entry.name.startsWith(".")) continue;
    if (entry.isDirectory()) {
      if (!IGNORED_DIRS.has(entry.name)) subdirs.push(entry.name);
    } else if (entry.name.toLowerCase().endsWith(".md") && !isReservedOkfFile(entry.name)) {
      const data = parseFrontmatter(fs.readFileSync(path.join(dir, entry.name), "utf-8")).data;
      const title = typeof data.title === "string" && data.title.trim()
        ? data.title
        : parseFilename(entry.name).title;
      const description = typeof data.description === "string" ? data.description : "";
      concepts.push({ file: entry.name, title, description });
    }
  }
  concepts.sort((a, b) => a.file.localeCompare(b.file));
  subdirs.sort((a, b) => a.localeCompare(b));
  return { concepts, subdirs };
}

// Depth-first: build children first so a directory can decide it is non-empty.
function generateForDir(root: string, dir: string): number {
  const { concepts, subdirs } = conceptsAndDirs(dir);
  let written = 0;
  for (const sub of subdirs) written += generateForDir(root, path.join(dir, sub));

  const isRoot = path.resolve(dir) === path.resolve(root);
  if (!isRoot && concepts.length === 0 && subdirs.length === 0) return written;

  const name = path.basename(path.resolve(dir));
  let md = isRoot ? `---\nokf_version: "${OKF_SPEC_VERSION}"\n---\n\n` : "";
  md += `# ${name}\n`;
  if (concepts.length) {
    md += "\n## Concepts\n\n";
    for (const c of concepts) {
      md += `* [${c.title}](./${c.file})${c.description ? ` - ${c.description}` : ""}\n`;
    }
  }
  if (subdirs.length) {
    md += "\n## Directories\n\n";
    for (const s of subdirs) md += `* [${s}](./${s}/index.md)\n`;
  }
  fs.writeFileSync(path.join(dir, "index.md"), md.endsWith("\n") ? md : `${md}\n`, "utf-8");
  return written + 1;
}

/** Generate all `index.md` files for the bundle; returns how many were written. */
export function generateOkfIndexFiles(docsPath: string): number {
  return generateForDir(docsPath, docsPath);
}
