// Snippets — picker grid configuration and emoji catalogue (ported from snippets.js).

export const SNIPPET_PANELS = [
  "heading",
  "collapsible",
  "link",
  "doc-link",
  "anchor-link",
  "anchor-doc-link",
  "ordered-list",
  "unordered-list",
  "code-block",
  "blockquote",
  "image",
  "table",
  "tree",
  "mermaid",
  "diagram",
  "colored-section",
  "colored-text",
  "emojis",
  "attachment",
  "compare",
  "columns",
  "kanban",
];

const SNIPPET_TYPE_TO_PANEL: Record<string, string> = {
  "heading-1": "heading",
  "heading-2": "heading",
  "heading-3": "heading",
  "heading-4": "heading",
};

export function snippetPanelForType(type: string): string {
  return SNIPPET_TYPE_TO_PANEL[type] || type;
}

export const SNIPPET_PICKER_ICONS: Record<string, string> = {
  "heading-1": "fa-solid fa-heading",
  "heading-2": "fa-solid fa-heading",
  "heading-3": "fa-solid fa-heading",
  "heading-4": "fa-solid fa-heading",
  separator: "fa-solid fa-minus",
  collapsible: "fa-solid fa-caret-right",
  "unordered-list": "fa-solid fa-list-ul",
  "ordered-list": "fa-solid fa-list-ol",
  tree: "fa-solid fa-folder-tree",
  "colored-text": "fa-solid fa-highlighter",
  "colored-section": "fa-solid fa-fill-drip",
  blockquote: "fa-solid fa-quote-right",
  "code-block": "fa-solid fa-code",
  table: "fa-solid fa-table-cells",
  mermaid: "fa-solid fa-chart-pie",
  link: "fa-solid fa-link",
  "doc-link": "fa-solid fa-file-lines",
  "anchor-link": "fa-solid fa-anchor",
  "anchor-doc-link": "fa-solid fa-anchor",
  image: "fa-solid fa-image",
  diagram: "fa-solid fa-diagram-project",
  emojis: "fa-solid fa-face-smile",
  attachment: "fa-solid fa-paperclip",
  "local-search": "fa-solid fa-magnifying-glass",
  "compare": "fa-solid fa-table-columns",
  columns: "fa-solid fa-table-columns",
  kanban: "fa-solid fa-table-columns",
};

export const SNIPPET_PICKER_CATEGORIES = [
  {
    key: "structure",
    labelKey: "snippet.picker_cat_structure",
    types: [
      "heading-1",
      "heading-2",
      "heading-3",
      "heading-4",
      "separator",
      "collapsible",
      "columns",
      "unordered-list",
      "ordered-list",
      "table",
      "kanban",
    ],
  },
  {
    key: "lists-code-data",
    labelKey: "snippet.picker_cat_lists_code_data",
    types: ["tree", "code-block", "mermaid", "diagram", "compare"],
  },
  {
    key: "rich-text",
    labelKey: "snippet.picker_cat_rich_text",
    types: ["colored-text", "colored-section", "blockquote", "emojis", "local-search"],
  },
  {
    key: "links-media",
    labelKey: "snippet.picker_cat_links_media",
    types: ["link", "doc-link", "anchor-link", "anchor-doc-link", "image", "attachment"],
  },
];

export const SNIPPET_PICKER_PALETTE: Record<string, { card: string; icon: string }> = {
  blueLight: { card: "border-sky-200 dark:border-sky-800 bg-sky-50 dark:bg-sky-950/40 hover:bg-sky-100 dark:hover:bg-sky-900/50 hover:border-sky-300 dark:hover:border-sky-700", icon: "text-sky-700 dark:text-sky-300" },
  blue: { card: "border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-950/40 hover:bg-blue-100 dark:hover:bg-blue-900/50 hover:border-blue-300 dark:hover:border-blue-700", icon: "text-blue-700 dark:text-blue-300" },
  blueDark: { card: "border-indigo-200 dark:border-indigo-800 bg-indigo-50 dark:bg-indigo-950/40 hover:bg-indigo-100 dark:hover:bg-indigo-900/50 hover:border-indigo-300 dark:hover:border-indigo-700", icon: "text-indigo-700 dark:text-indigo-300" },
  blueDarker: { card: "border-blue-300 dark:border-blue-700 bg-blue-100 dark:bg-blue-900/50 hover:bg-blue-200 dark:hover:bg-blue-800/60 hover:border-blue-400 dark:hover:border-blue-600", icon: "text-blue-900 dark:text-blue-100" },
  gray: { card: "border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 hover:border-gray-300 dark:hover:border-gray-600", icon: "text-gray-700 dark:text-gray-200" },
  violet: { card: "border-violet-200 dark:border-violet-800 bg-violet-50 dark:bg-violet-950/40 hover:bg-violet-100 dark:hover:bg-violet-900/50 hover:border-violet-300 dark:hover:border-violet-700", icon: "text-violet-700 dark:text-violet-300" },
  green: { card: "border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/40 hover:bg-emerald-100 dark:hover:bg-emerald-900/50 hover:border-emerald-300 dark:hover:border-emerald-700", icon: "text-emerald-700 dark:text-emerald-300" },
  greenDark: { card: "border-green-300 dark:border-green-700 bg-green-100 dark:bg-green-900/50 hover:bg-green-200 dark:hover:bg-green-800/60 hover:border-green-400 dark:hover:border-green-600", icon: "text-green-900 dark:text-green-100" },
  teal: { card: "border-teal-200 dark:border-teal-800 bg-teal-50 dark:bg-teal-950/40 hover:bg-teal-100 dark:hover:bg-teal-900/50 hover:border-teal-300 dark:hover:border-teal-700", icon: "text-teal-700 dark:text-teal-300" },
  dark: { card: "border-slate-300 dark:border-slate-600 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 hover:border-slate-400 dark:hover:border-slate-500", icon: "text-slate-900 dark:text-slate-100" },
  orange: { card: "border-orange-200 dark:border-orange-800 bg-orange-50 dark:bg-orange-950/40 hover:bg-orange-100 dark:hover:bg-orange-900/50 hover:border-orange-300 dark:hover:border-orange-700", icon: "text-orange-700 dark:text-orange-300" },
  orangeLight: { card: "border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/40 hover:bg-amber-100 dark:hover:bg-amber-900/50 hover:border-amber-300 dark:hover:border-amber-700", icon: "text-amber-700 dark:text-amber-300" },
  orangeDark: { card: "border-orange-300 dark:border-orange-700 bg-orange-100 dark:bg-orange-900/50 hover:bg-orange-200 dark:hover:bg-orange-800/60 hover:border-orange-400 dark:hover:border-orange-600", icon: "text-orange-900 dark:text-orange-100" },
  red: { card: "border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-950/40 hover:bg-red-100 dark:hover:bg-red-900/50 hover:border-red-300 dark:hover:border-red-700", icon: "text-red-700 dark:text-red-300" },
  pink: { card: "border-pink-200 dark:border-pink-800 bg-pink-50 dark:bg-pink-950/40 hover:bg-pink-100 dark:hover:bg-pink-900/50 hover:border-pink-300 dark:hover:border-pink-700", icon: "text-pink-700 dark:text-pink-300" },
  amber: { card: "border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/40 hover:bg-amber-100 dark:hover:bg-amber-900/50 hover:border-amber-300 dark:hover:border-amber-700", icon: "text-amber-700 dark:text-amber-300" },
  yellow: { card: "border-yellow-300 dark:border-yellow-700 bg-yellow-100 dark:bg-yellow-900/50 hover:bg-yellow-200 dark:hover:bg-yellow-800/60 hover:border-yellow-400 dark:hover:border-yellow-600", icon: "text-yellow-700 dark:text-yellow-200" },
  indigo: { card: "border-indigo-200 dark:border-indigo-800 bg-indigo-50 dark:bg-indigo-950/40 hover:bg-indigo-100 dark:hover:bg-indigo-900/50 hover:border-indigo-300 dark:hover:border-indigo-700", icon: "text-indigo-700 dark:text-indigo-300" },
  cyan: { card: "border-cyan-200 dark:border-cyan-800 bg-cyan-50 dark:bg-cyan-950/40 hover:bg-cyan-100 dark:hover:bg-cyan-900/50 hover:border-cyan-300 dark:hover:border-cyan-700", icon: "text-cyan-700 dark:text-cyan-300" },
};

export const SNIPPET_PICKER_TYPE_PALETTE: Record<string, string> = {
  "heading-1": "blueLight",
  "heading-2": "blue",
  "heading-3": "blueDark",
  "heading-4": "blueDarker",
  separator: "gray",
  collapsible: "dark",
  "unordered-list": "green",
  "ordered-list": "greenDark",
  tree: "cyan",
  "code-block": "dark",
  mermaid: "teal",
  table: "orange",
  diagram: "red",
  "colored-text": "pink",
  "colored-section": "violet",
  blockquote: "gray",
  link: "orangeLight",
  "doc-link": "orange",
  "anchor-link": "orangeDark",
  "anchor-doc-link": "orangeDark",
  image: "amber",
  attachment: "orange",
  emojis: "yellow",
  "local-search": "cyan",
  "compare": "teal",
  columns: "teal",
  kanban: "violet",
};

export const SNIPPET_TYPE_I18N_KEY: Record<string, string> = {
  "heading-1": "snippet.heading_1",
  "heading-2": "snippet.heading_2",
  "heading-3": "snippet.heading_3",
  "heading-4": "snippet.heading_4",
  separator: "snippet.separator",
  collapsible: "snippet.collapsible",
  "unordered-list": "snippet.bullet_list",
  "ordered-list": "snippet.numbered_list",
  tree: "snippet.tree",
  "colored-text": "snippet.colored_text",
  "colored-section": "snippet.colored_section",
  blockquote: "snippet.blockquote",
  "code-block": "snippet.code_block",
  mermaid: "snippet.mermaid",
  table: "snippet.table",
  link: "snippet.link",
  "doc-link": "snippet.link_doc",
  "anchor-link": "snippet.link_anchor",
  "anchor-doc-link": "snippet.link_doc_anchor",
  image: "snippet.image",
  diagram: "snippet.diagram",
  emojis: "snippet.emojis",
  attachment: "snippet.attachment",
  "local-search": "snippet.local_search",
  "compare": "snippet.compare",
  columns: "snippet.columns",
  kanban: "snippet.kanban",
};

export const COLOR_SWATCHES: Record<string, { bg: string; border: string; text: string }> = {
  info: { bg: "#eff6ff", border: "#3b82f6", text: "#1e3a5f" },
  success: { bg: "#f0fdf4", border: "#22c55e", text: "#14532d" },
  warning: { bg: "#fffbeb", border: "#f59e0b", text: "#451a03" },
  danger: { bg: "#fef2f2", border: "#ef4444", text: "#450a0a" },
  note: { bg: "#f5f3ff", border: "#8b5cf6", text: "#2e1065" },
  neutral: { bg: "#f9fafb", border: "#6b7280", text: "#111827" },
};

export interface EmojiItem {
  e: string;
  t: string;
}
export interface EmojiCategory {
  label: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { label: 'snippet.emoji_cat_smileys', emojis: [
    { e: '😀', t: 'grin grinning smile sourire happy heureux' },
    { e: '😃', t: 'smiley joy joie sourire happy' },
    { e: '😄', t: 'smile sourire happy heureux joie' },
    { e: '😁', t: 'beaming grin sourire dents' },
    { e: '😆', t: 'laugh rire lol' },
    { e: '😅', t: 'sweat transpire rire nerveux' },
    { e: '🤣', t: 'rofl lol mdr rire' },
    { e: '😂', t: 'joy larmes tears rire lol' },
    { e: '🙂', t: 'slight smile sourire' },
    { e: '🙃', t: 'upside renverse inverse' },
    { e: '😉', t: 'wink clin oeil' },
    { e: '😊', t: 'blush rougir sourire' },
    { e: '😇', t: 'angel ange halo innocent' },
    { e: '🥰', t: 'love amour coeur heart smile' },
    { e: '😍', t: 'heart eyes amoureux love amour' },
    { e: '🤩', t: 'star stars etoile wow' },
    { e: '😘', t: 'kiss bisou' },
    { e: '😋', t: 'yum miam savoureux langue' },
    { e: '😛', t: 'tongue langue' },
    { e: '😜', t: 'wink tongue langue clin' },
    { e: '🤪', t: 'crazy fou zany' },
    { e: '😝', t: 'tongue langue squinting' },
    { e: '🤗', t: 'hug calin embrasser' },
    { e: '🤔', t: 'think reflexion reflechir pense' },
    { e: '🤨', t: 'raised brow sourcil suspicious' },
    { e: '😐', t: 'neutral neutre' },
    { e: '😑', t: 'expressionless impassible' },
    { e: '😒', t: 'unamused decu blase' },
    { e: '🙄', t: 'roll eyes yeux ciel' },
    { e: '😬', t: 'grimace' },
    { e: '😌', t: 'relieved soulage' },
    { e: '😔', t: 'pensive pensif triste sad' },
    { e: '😪', t: 'sleepy sommeil fatigue' },
    { e: '😴', t: 'sleep dormir zzz' },
    { e: '🤤', t: 'drool bave' },
    { e: '😷', t: 'mask masque malade' },
    { e: '🤒', t: 'sick malade fever fievre' },
    { e: '🤕', t: 'hurt blesse bandage' },
    { e: '🤢', t: 'nausea nausee' },
    { e: '🤮', t: 'vomit vomir malade' },
    { e: '🤧', t: 'sneeze eternue rhume' },
    { e: '🥵', t: 'hot chaud transpire' },
    { e: '🥶', t: 'cold froid gele' },
    { e: '🥴', t: 'woozy ivre' },
    { e: '😵', t: 'dizzy dead mort vertige' },
    { e: '🤯', t: 'explode tete mind blown' },
    { e: '🤠', t: 'cowboy chapeau' },
    { e: '🥳', t: 'party fete anniversaire birthday' },
    { e: '😎', t: 'cool sunglasses lunettes' },
    { e: '🤓', t: 'nerd geek' },
    { e: '🧐', t: 'monocle curious' },
    { e: '😕', t: 'confused confus' },
    { e: '😟', t: 'worried inquiet' },
    { e: '🙁', t: 'frown triste' },
    { e: '☹️', t: 'sad triste frown' },
    { e: '😮', t: 'surprised surpris open mouth' },
    { e: '😯', t: 'hushed' },
    { e: '😲', t: 'astonished etonne' },
    { e: '😳', t: 'flushed gene rougeur' },
    { e: '🥺', t: 'pleading supplier chien' },
    { e: '😦', t: 'frown open mouth' },
    { e: '😧', t: 'anguish angoisse' },
    { e: '😨', t: 'fear peur' },
    { e: '😰', t: 'anxious anxieux stress' },
    { e: '😥', t: 'sad disappointed decu' },
    { e: '😢', t: 'cry pleurer larme' },
    { e: '😭', t: 'cry pleurer loud bawling' },
    { e: '😱', t: 'scream cri peur horror' },
    { e: '😖', t: 'confounded' },
    { e: '😣', t: 'persevere effort' },
    { e: '😞', t: 'disappointed decu' },
    { e: '😓', t: 'sweat transpire fatigue' },
    { e: '😩', t: 'weary fatigue las' },
    { e: '😫', t: 'tired fatigue' },
    { e: '🥱', t: 'yawn baille' },
    { e: '😤', t: 'triumph huff vapeur nez' },
    { e: '😠', t: 'angry colere fache' },
    { e: '😡', t: 'rage colere rouge' },
    { e: '🤬', t: 'curse insulte jure' },
    { e: '😈', t: 'devil diable smiling' },
    { e: '👿', t: 'imp diable' },
    { e: '💀', t: 'skull mort death crane' },
    { e: '☠️', t: 'crossbones pirate mort death' },
    { e: '💩', t: 'poop caca merde' },
    { e: '🤡', t: 'clown' },
    { e: '👻', t: 'ghost fantome' },
    { e: '👽', t: 'alien extraterrestre' },
    { e: '🤖', t: 'robot ia ai' },
    { e: '🎃', t: 'pumpkin halloween citrouille' },
    { e: '😺', t: 'cat chat' },
    { e: '😸', t: 'cat chat grin' },
    { e: '😹', t: 'cat chat joy' },
    { e: '😻', t: 'cat chat love amour heart' },
    { e: '😼', t: 'cat chat wry' },
    { e: '😽', t: 'cat chat kiss' },
    { e: '🙀', t: 'cat chat fear peur' },
    { e: '😿', t: 'cat chat cry pleurer' },
    { e: '😾', t: 'cat chat angry colere' },
  ]},
  { label: 'snippet.emoji_cat_gestures', emojis: [
    { e: '👍', t: 'thumbs up pouce ok bien like' },
    { e: '👎', t: 'thumbs down pouce bas dislike' },
    { e: '👌', t: 'ok parfait' },
    { e: '✌️', t: 'victory victoire peace paix' },
    { e: '🤞', t: 'fingers crossed doigts croises' },
    { e: '🤟', t: 'love you' },
    { e: '🤘', t: 'rock horns metal cornes' },
    { e: '🤙', t: 'call appelle hang loose' },
    { e: '👈', t: 'left gauche pointing' },
    { e: '👉', t: 'right droite pointing' },
    { e: '👆', t: 'up haut pointing' },
    { e: '👇', t: 'down bas pointing' },
    { e: '☝️', t: 'one index up haut' },
    { e: '✋', t: 'stop hand main raised' },
    { e: '🤚', t: 'back hand main' },
    { e: '🖐️', t: 'hand main splayed' },
    { e: '🖖', t: 'vulcan spock star trek' },
    { e: '👋', t: 'wave bonjour hello salut goodbye' },
    { e: '🤝', t: 'handshake accord deal poignee' },
    { e: '🙏', t: 'pray priere merci thanks please' },
    { e: '💪', t: 'muscle fort biceps strong' },
    { e: '🦾', t: 'mechanical arm bras prothese' },
    { e: '👏', t: 'clap applaud bravo applaudir' },
    { e: '🙌', t: 'raise hands hourra celebrate' },
    { e: '👐', t: 'open hands' },
    { e: '🤲', t: 'palms up paumes' },
    { e: '🤜', t: 'fist poing right' },
    { e: '🤛', t: 'fist poing left' },
    { e: '✊', t: 'fist poing leve' },
    { e: '👊', t: 'fist punch poing frapper' },
    { e: '🤏', t: 'pinch petit small' },
    { e: '🤌', t: 'italian pinched' },
    { e: '🖕', t: 'middle finger doigt honneur' },
    { e: '✍️', t: 'write ecrire hand main' },
    { e: '🦶', t: 'foot pied' },
    { e: '🦵', t: 'leg jambe' },
    { e: '👂', t: 'ear oreille' },
    { e: '🦻', t: 'ear hearing appareil auditif' },
    { e: '👃', t: 'nose nez' },
    { e: '🧠', t: 'brain cerveau mind' },
    { e: '👀', t: 'eyes yeux regarder' },
    { e: '👁️', t: 'eye oeil' },
    { e: '👄', t: 'mouth bouche' },
    { e: '👅', t: 'tongue langue' },
    { e: '🦷', t: 'tooth dent' },
    { e: '🫀', t: 'heart anatomic coeur organe' },
    { e: '🫁', t: 'lungs poumons' },
  ]},
  { label: 'snippet.emoji_cat_hearts', emojis: [
    { e: '❤️', t: 'heart coeur red rouge love amour' },
    { e: '🧡', t: 'orange heart coeur' },
    { e: '💛', t: 'yellow heart coeur jaune' },
    { e: '💚', t: 'green heart coeur vert' },
    { e: '💙', t: 'blue heart coeur bleu' },
    { e: '💜', t: 'purple heart coeur violet' },
    { e: '🖤', t: 'black heart coeur noir' },
    { e: '🤍', t: 'white heart coeur blanc' },
    { e: '🤎', t: 'brown heart coeur marron' },
    { e: '💔', t: 'broken heart coeur brise rupture' },
    { e: '❤️‍🔥', t: 'heart fire feu passion' },
    { e: '❤️‍🩹', t: 'heart mending coeur reparation' },
    { e: '💖', t: 'sparkling heart coeur brillant' },
    { e: '💕', t: 'two hearts coeurs' },
    { e: '💘', t: 'arrow heart cupid cupidon' },
    { e: '💝', t: 'ribbon heart cadeau' },
    { e: '💞', t: 'revolving hearts coeurs' },
    { e: '💟', t: 'heart decoration' },
    { e: '💌', t: 'love letter lettre enveloppe' },
    { e: '💋', t: 'kiss mark bisou levres' },
    { e: '❣️', t: 'heart exclamation' },
    { e: '💯', t: 'hundred 100 cent perfect parfait' },
    { e: '✨', t: 'sparkles etincelles magic magique brillant' },
    { e: '⭐', t: 'star etoile' },
    { e: '🌟', t: 'glowing star etoile' },
    { e: '💫', t: 'dizzy star vertige etoile' },
    { e: '🔥', t: 'fire feu hot flamme' },
    { e: '💥', t: 'boom explosion collision' },
    { e: '⚡', t: 'lightning eclair thunder tonnerre fast' },
    { e: '💢', t: 'anger colere symbol' },
    { e: '💨', t: 'dash vent wind fast vitesse' },
    { e: '💦', t: 'drops gouttes sweat eau' },
    { e: '💤', t: 'zzz sleep dormir sommeil' },
    { e: '🕳️', t: 'hole trou' },
    { e: '💭', t: 'thought pensee bulle' },
    { e: '🗯️', t: 'right anger bubble' },
    { e: '💬', t: 'speech bulle dialogue chat' },
  ]},
  { label: 'snippet.emoji_cat_objects', emojis: [
    { e: '💻', t: 'laptop ordinateur computer portable' },
    { e: '🖥️', t: 'desktop computer ordinateur bureau' },
    { e: '⌨️', t: 'keyboard clavier' },
    { e: '🖱️', t: 'mouse souris' },
    { e: '💾', t: 'floppy disquette save sauvegarder' },
    { e: '💿', t: 'disk cd optical' },
    { e: '📀', t: 'dvd' },
    { e: '📱', t: 'phone mobile telephone smartphone' },
    { e: '📲', t: 'phone call mobile incoming' },
    { e: '☎️', t: 'telephone vintage' },
    { e: '📞', t: 'receiver combine phone' },
    { e: '📟', t: 'pager' },
    { e: '📠', t: 'fax' },
    { e: '🔋', t: 'battery batterie pile' },
    { e: '🔌', t: 'plug prise electrique' },
    { e: '💡', t: 'bulb idee idea light lumiere ampoule' },
    { e: '🔦', t: 'flashlight torche lampe' },
    { e: '🕯️', t: 'candle bougie' },
    { e: '📷', t: 'camera appareil photo' },
    { e: '📸', t: 'camera flash photo' },
    { e: '📹', t: 'video camera' },
    { e: '🎥', t: 'movie film cinema camera' },
    { e: '🎞️', t: 'film reel pellicule' },
    { e: '📽️', t: 'projector projecteur' },
    { e: '⏰', t: 'alarm reveil clock horloge' },
    { e: '⏱️', t: 'stopwatch chrono chronometre' },
    { e: '⏲️', t: 'timer minuteur' },
    { e: '🕰️', t: 'mantel clock horloge' },
    { e: '⌛', t: 'hourglass sablier done' },
    { e: '⏳', t: 'hourglass sablier flow running' },
    { e: '📡', t: 'satellite antenne' },
    { e: '🔭', t: 'telescope astronomie' },
    { e: '🔬', t: 'microscope science' },
    { e: '💊', t: 'pill pilule medicine medicament' },
    { e: '💉', t: 'syringe seringue injection vaccin' },
    { e: '🩹', t: 'bandage pansement' },
    { e: '🩺', t: 'stethoscope medecin' },
    { e: '🧪', t: 'tube eprouvette chimie chemistry' },
    { e: '🧬', t: 'dna adn gene' },
    { e: '🔍', t: 'search magnify loupe rechercher find left' },
    { e: '🔎', t: 'search magnify loupe rechercher find right' },
    { e: '🗝️', t: 'key cle old' },
    { e: '🔑', t: 'key cle' },
    { e: '🔐', t: 'lock key cle cadenas' },
    { e: '🔒', t: 'lock cadenas verrouille secure' },
    { e: '🔓', t: 'unlock cadenas ouvert' },
    { e: '🛡️', t: 'shield bouclier protection' },
    { e: '🔨', t: 'hammer marteau' },
    { e: '⚒️', t: 'tools outils hammer pick' },
    { e: '🛠️', t: 'tools outils hammer wrench' },
    { e: '🔧', t: 'wrench cle anglaise' },
    { e: '🔩', t: 'nut bolt ecrou' },
    { e: '⚙️', t: 'gear settings parametres engrenage config' },
    { e: '🪛', t: 'screwdriver tournevis' },
    { e: '🪝', t: 'hook crochet' },
    { e: '🧰', t: 'toolbox caisse outils' },
    { e: '🧲', t: 'magnet aimant' },
    { e: '🧱', t: 'brick brique' },
    { e: '⛏️', t: 'pick pioche' },
    { e: '🪓', t: 'axe hache' },
  ]},
  { label: 'snippet.emoji_cat_office', emojis: [
    { e: '📝', t: 'memo note ecrire write' },
    { e: '✏️', t: 'pencil crayon' },
    { e: '🖊️', t: 'pen stylo bille' },
    { e: '🖋️', t: 'fountain pen stylo plume' },
    { e: '🖌️', t: 'paintbrush pinceau' },
    { e: '🖍️', t: 'crayon feutre' },
    { e: '📐', t: 'triangle ruler equerre' },
    { e: '📏', t: 'ruler regle' },
    { e: '📎', t: 'paperclip trombone attach' },
    { e: '🖇️', t: 'linked paperclips trombones' },
    { e: '📌', t: 'pushpin punaise' },
    { e: '📍', t: 'pin location lieu' },
    { e: '✂️', t: 'scissors ciseaux cut couper' },
    { e: '🗂️', t: 'card index dividers onglets' },
    { e: '📁', t: 'folder dossier' },
    { e: '📂', t: 'open folder dossier ouvert' },
    { e: '🗃️', t: 'card box boite fiches' },
    { e: '🗄️', t: 'file cabinet archive armoire' },
    { e: '📋', t: 'clipboard presse papier' },
    { e: '📃', t: 'page curl document' },
    { e: '📄', t: 'document page' },
    { e: '📜', t: 'scroll parchemin' },
    { e: '📰', t: 'newspaper journal presse' },
    { e: '🗞️', t: 'rolled newspaper journal' },
    { e: '📓', t: 'notebook carnet cahier' },
    { e: '📔', t: 'notebook decorated carnet' },
    { e: '📒', t: 'ledger registre' },
    { e: '📕', t: 'book rouge red ferme' },
    { e: '📗', t: 'book vert green' },
    { e: '📘', t: 'book bleu blue' },
    { e: '📙', t: 'book orange' },
    { e: '📚', t: 'books livres bibliotheque' },
    { e: '📖', t: 'open book livre ouvert' },
    { e: '🔖', t: 'bookmark marque page signet' },
    { e: '🏷️', t: 'label tag etiquette' },
    { e: '💼', t: 'briefcase mallette attache case business' },
    { e: '🗒️', t: 'spiral note notepad' },
    { e: '🗓️', t: 'spiral calendar calendrier' },
    { e: '📅', t: 'calendar calendrier date' },
    { e: '📆', t: 'tear off calendar calendrier' },
    { e: '🗑️', t: 'trash poubelle delete supprimer can' },
    { e: '🪣', t: 'bucket seau' },
    { e: '📦', t: 'package colis box boite' },
    { e: '📫', t: 'mailbox boite lettres closed flag up' },
    { e: '📪', t: 'mailbox boite lettres closed flag down' },
    { e: '📬', t: 'mailbox open boite lettres flag up' },
    { e: '📭', t: 'mailbox open boite lettres flag down' },
    { e: '📮', t: 'postbox boite aux lettres' },
    { e: '✉️', t: 'envelope enveloppe' },
    { e: '📧', t: 'email courriel mail at' },
    { e: '📨', t: 'email incoming recu' },
    { e: '📩', t: 'email arrow envoi' },
    { e: '📤', t: 'outbox envoyer sent' },
    { e: '📥', t: 'inbox recevoir' },
    { e: '📊', t: 'bar chart graphique barres histogramme' },
    { e: '📈', t: 'chart up tendance hausse croissance' },
    { e: '📉', t: 'chart down baisse decroissance' },
  ]},
  { label: 'snippet.emoji_cat_symbols', emojis: [
    { e: '🆕', t: 'new nouveau nouvelle brand fresh neuf' },
    { e: '♻️', t: 'existing existant existante recycle recycler reuse reutiliser' },
    { e: '✅', t: 'check ok valide coche green' },
    { e: '☑️', t: 'check ballot case' },
    { e: '✔️', t: 'check coche mark' },
    { e: '❌', t: 'cross error erreur red rouge croix ko' },
    { e: '✖️', t: 'multiply multiplier cross' },
    { e: '❎', t: 'cross square button' },
    { e: '⚠️', t: 'warning attention danger' },
    { e: 'ℹ️', t: 'info information' },
    { e: '❓', t: 'question red interrogation' },
    { e: '❔', t: 'question white interrogation' },
    { e: '❗', t: 'exclamation important red' },
    { e: '❕', t: 'exclamation white' },
    { e: '‼️', t: 'double exclamation' },
    { e: '⁉️', t: 'exclamation question' },
    { e: '🚀', t: 'rocket fusee launch lancer' },
    { e: '🎉', t: 'party popper tada fete celebration' },
    { e: '🎊', t: 'confetti ball fete' },
    { e: '🏆', t: 'trophy trophee winner' },
    { e: '🥇', t: 'gold medal medaille or first' },
    { e: '🥈', t: 'silver medal medaille argent second' },
    { e: '🥉', t: 'bronze medal medaille third' },
    { e: '🏅', t: 'medal medaille sports' },
    { e: '🎖️', t: 'military medal medaille' },
    { e: '🎯', t: 'target cible dart' },
    { e: '🎁', t: 'gift cadeau present' },
    { e: '🔔', t: 'bell cloche notify notification' },
    { e: '🔕', t: 'bell off muted silence' },
    { e: '📢', t: 'loudspeaker annonce public' },
    { e: '📣', t: 'megaphone porte voix' },
    { e: '📯', t: 'postal horn cor' },
    { e: '➕', t: 'plus add heavy' },
    { e: '➖', t: 'minus moins heavy' },
    { e: '➗', t: 'divide division' },
    { e: '♾️', t: 'infinity infini' },
    { e: '💲', t: 'dollar sign dollars money argent' },
    { e: '💱', t: 'currency exchange change devise' },
    { e: '©️', t: 'copyright' },
    { e: '®️', t: 'registered' },
    { e: '™️', t: 'trademark marque' },
    { e: '↔️', t: 'left right arrow fleche horizontal' },
    { e: '↕️', t: 'up down arrow fleche vertical' },
    { e: '↖️', t: 'up left arrow fleche' },
    { e: '↗️', t: 'up right arrow fleche' },
    { e: '↘️', t: 'down right arrow fleche' },
    { e: '↙️', t: 'down left arrow fleche' },
    { e: '⬅️', t: 'left arrow fleche gauche' },
    { e: '➡️', t: 'right arrow fleche droite' },
    { e: '⬆️', t: 'up arrow fleche haut' },
    { e: '⬇️', t: 'down arrow fleche bas' },
    { e: '🔃', t: 'clockwise vertical arrows' },
    { e: '🔄', t: 'counterclockwise arrows reload refresh recharger' },
    { e: '🔁', t: 'repeat loop boucle' },
    { e: '🔂', t: 'repeat single once' },
    { e: '🔀', t: 'shuffle melange random' },
    { e: '🔼', t: 'up button triangle' },
    { e: '🔽', t: 'down button triangle' },
    { e: '⏫', t: 'fast up double triangle' },
    { e: '⏬', t: 'fast down double triangle' },
    { e: '⏪', t: 'rewind back' },
    { e: '⏩', t: 'fast forward avance' },
    { e: '⏭️', t: 'next track suivant' },
    { e: '⏮️', t: 'previous track precedent' },
    { e: '⏯️', t: 'play pause' },
    { e: '▶️', t: 'play lecture' },
    { e: '⏸️', t: 'pause' },
    { e: '⏹️', t: 'stop' },
    { e: '⏺️', t: 'record enregistrer' },
    { e: '⏏️', t: 'eject ejecter' },
    { e: '🎵', t: 'music note musique' },
    { e: '🎶', t: 'music notes musique' },
    { e: '🔈', t: 'speaker low bas' },
    { e: '🔉', t: 'speaker medium moyen' },
    { e: '🔊', t: 'speaker loud fort haut son sound' },
    { e: '🔇', t: 'muted mute silence' },
    { e: '📶', t: 'signal antenne bars' },
    { e: '🛜', t: 'wireless wifi' },
    { e: '🔗', t: 'link lien chain' },
    { e: '⛓️', t: 'chains chaine' },
    { e: '🏁', t: 'finish flag checkered fin arrivee' },
    { e: '🚩', t: 'flag drapeau triangular' },
    { e: '🏳️', t: 'white flag drapeau blanc' },
    { e: '🏴', t: 'black flag drapeau noir' },
    { e: '🏳️‍🌈', t: 'rainbow lgbt pride drapeau arc en ciel' },
    { e: '🏳️‍⚧️', t: 'trans drapeau transgender' },
    { e: '🏴‍☠️', t: 'pirate drapeau jolly roger' },
  ]},
];
